// services/cif/src/test/java/com/buildabank/cif/dblab/PartitioningLabTest.java
package com.buildabank.cif.dblab;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * <strong>Declarative range partitioning &amp; partition pruning.</strong> A huge transactions table is
 * split into monthly child tables; a query restricted to one month should touch <em>only</em> that month's
 * partition. We prove it by reading the plan: the other partitions never appear.
 *
 * <p>Why a bank cares: an EOD/statement query over "last month" scans one small partition instead of years
 * of history, and dropping old data becomes an instant {@code DROP TABLE partition} instead of a giant,
 * lock-heavy {@code DELETE}.
 */
class PartitioningLabTest extends DbLab {

    @BeforeAll
    static void seed() throws Exception {
        try (Connection c = openAuto()) {
            exec(c, "drop table if exists txn_part cascade");
            exec(c, """
                    create table txn_part (
                        id         bigint generated by default as identity,
                        account_id bigint         not null,
                        amount     numeric(19, 4) not null,
                        created_at date           not null
                    ) partition by range (created_at)""");
            exec(c, "create table txn_2026_01 partition of txn_part "
                    + "for values from ('2026-01-01') to ('2026-02-01')");
            exec(c, "create table txn_2026_02 partition of txn_part "
                    + "for values from ('2026-02-01') to ('2026-03-01')");
            exec(c, "create table txn_2026_03 partition of txn_part "
                    + "for values from ('2026-03-01') to ('2026-04-01')");
            // ~900 rows spread across the three months (day = Jan 1 + 0..88).
            exec(c, """
                    insert into txn_part (account_id, amount, created_at)
                    select g,
                           (random() * 100)::numeric(19, 4),
                           date '2026-01-01' + (g % 89)
                    from generate_series(1, 900) as g""");
            exec(c, "analyze txn_part");
        }
    }

    @Test
    void queryForOneMonthPrunesToASinglePartition() throws Exception {
        try (Connection c = openAuto()) {
            String plan = explain(c, """
                    select count(*) from txn_part
                    where created_at >= date '2026-02-01' and created_at < date '2026-03-01'""", true);
            System.out.println("\n=== PARTITION PRUNING — expect only txn_2026_02 scanned ===\n" + plan);

            assertThat(plan).contains("txn_2026_02");          // the matching partition is scanned
            assertThat(plan).doesNotContain("txn_2026_01");     // the others are pruned away
            assertThat(plan).doesNotContain("txn_2026_03");
        }
    }
}
