// services/cif/src/test/java/com/buildabank/cif/dblab/QueryPlanLabTest.java
package com.buildabank.cif.dblab;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * <strong>Indexing &amp; query plans.</strong> Seeds 20,000 transaction rows into a real Postgres, then
 * uses {@code EXPLAIN (ANALYZE)} to <em>watch the planner change its mind</em>:
 *
 * <ol>
 *   <li>no index → <strong>Seq Scan</strong> (read every row);</li>
 *   <li>add a B-tree index + {@code ANALYZE} → <strong>Index Scan</strong> (jump straight to the rows);</li>
 *   <li>a <strong>covering</strong> index ({@code INCLUDE (amount)}) + {@code VACUUM} → <strong>Index Only
 *       Scan</strong> (answer the query from the index alone, never touching the heap).</li>
 * </ol>
 *
 * The plan text is printed so you can read the real output; the assertions check the <em>node type</em>,
 * which is stable run-to-run (timings are not).
 */
class QueryPlanLabTest extends DbLab {

    @BeforeAll
    static void seed() throws Exception {
        try (Connection c = openAuto()) {
            exec(c, "drop table if exists txn");
            exec(c, """
                    create table txn (
                        id         bigint generated by default as identity primary key,
                        account_id bigint         not null,
                        amount     numeric(19, 4) not null,
                        created_at timestamptz    not null
                    )""");
            // 20,000 rows spread over 5,000 accounts → ~4 rows per account (a highly selective lookup).
            exec(c, """
                    insert into txn (account_id, amount, created_at)
                    select (g % 5000),
                           (random() * 1000)::numeric(19, 4),
                           now() - make_interval(mins => g)
                    from generate_series(1, 20000) as g""");
        }
    }

    @Test
    void seqScan_thenIndexScan_thenIndexOnlyScan() throws Exception {
        try (Connection c = openAuto()) {

            // 1 ── No index yet: the only way to find account 42's rows is to read all 20,000.
            String beforeIndex = explain(c, "select * from txn where account_id = 42", true);
            System.out.println("\n=== [1] NO INDEX — expect Seq Scan ===\n" + beforeIndex);
            assertThat(beforeIndex).contains("Seq Scan on txn");

            // 2 ── Add a B-tree index and refresh the planner's statistics.
            exec(c, "create index idx_txn_account on txn (account_id)");
            exec(c, "analyze txn");
            String afterIndex = explain(c, "select * from txn where account_id = 42", true);
            System.out.println("\n=== [2] WITH INDEX — expect Index Scan ===\n" + afterIndex);
            assertThat(afterIndex).contains("Index Scan").doesNotContain("Seq Scan on txn");

            // 3 ── Covering index: include `amount` IN the index so a query needing only
            //      (account_id, amount) is answered from the index alone — an Index Only Scan.
            //      VACUUM sets the visibility map so the heap need not be consulted for visibility.
            exec(c, "create index idx_txn_account_amount on txn (account_id) include (amount)");
            exec(c, "vacuum analyze txn");
            String covering = explain(c,
                    "select account_id, amount from txn where account_id = 42", true);
            System.out.println("\n=== [3] COVERING INDEX — expect Index Only Scan ===\n" + covering);
            assertThat(covering).contains("Index Only Scan");
        }
    }
}
