-- steps/step-10/queries.sql — Step 10 interactive SQL lab ("Play With It").
--
-- Everything Step 10 proves in JUnit, you can also run BY HAND in psql to *feel* it. This file is the
-- copy-paste companion. Two ways to get a Postgres shell:
--
--   A) Spin up a throwaway Postgres in Docker (recommended — nothing to install, easy to delete):
--        docker run --rm -d --name pg-lab -e POSTGRES_PASSWORD=lab -p 5433:5432 postgres:17-alpine
--        docker exec -it pg-lab psql -U postgres
--      (host port 5433 avoids the local Postgres that already owns 5432 on this machine — see CAPABILITIES.md)
--      When done:  docker rm -f pg-lab
--
--   B) Any psql pointed at any Postgres 14+.
--
-- Run the blocks below in order. For the concurrency blocks (§3, §4) open TWO psql sessions side by side
-- (session 1 and session 2) and run the lines in the labelled order — that is the whole point.
-- ============================================================================================================

-- ── §1 · Indexing & query plans (seq scan → index scan → index-only scan) ──────────────────────────────────
drop table if exists txn;
create table txn (
    id         bigint generated by default as identity primary key,
    account_id bigint         not null,
    amount     numeric(19, 4) not null,
    created_at timestamptz    not null
);
insert into txn (account_id, amount, created_at)
select (g % 5000), (random() * 1000)::numeric(19, 4), now() - make_interval(mins => g)
from generate_series(1, 20000) as g;

-- No index yet → Seq Scan (reads all 20,000 rows, "Rows Removed by Filter: 19996").
explain (analyze, buffers) select * from txn where account_id = 42;

-- Add a B-tree index + refresh stats → the planner switches to an Index/Bitmap scan.
create index idx_txn_account on txn (account_id);
analyze txn;
explain (analyze, buffers) select * from txn where account_id = 42;

-- A COVERING index (INCLUDE the columns the query reads) + VACUUM (sets the visibility map) → Index Only Scan,
-- "Heap Fetches: 0" — the query is answered from the index alone, never touching the table heap.
create index idx_txn_account_amount on txn (account_id) include (amount);
vacuum analyze txn;
explain (analyze, buffers) select account_id, amount from txn where account_id = 42;


-- ── §2 · MVCC: who sees what ──────────────────────────────────────────────────────────────────────────────
drop table if exists acct;
create table acct (id int primary key, balance numeric not null);
insert into acct values (1, 100), (2, 100);

-- Every row carries hidden system columns. xmin = the transaction that created this row version.
select id, balance, xmin, xmax from acct;
select txid_current();   -- your current transaction id


-- ── §3 · Non-repeatable read (run in TWO sessions) ─────────────────────────────────────────────────────────
-- session 1:  begin transaction isolation level read committed;
-- session 1:  select balance from acct where id = 1;          -- 100
-- session 2:  update acct set balance = 200 where id = 1;     -- (autocommit) commits immediately
-- session 1:  select balance from acct where id = 1;          -- 200  ← changed under your feet (non-repeatable)
-- session 1:  rollback;
--
-- Now repeat with REPEATABLE READ and watch the second read stay 100:
-- session 1:  begin transaction isolation level repeatable read;
-- session 1:  select balance from acct where id = 1;          -- 100  (snapshot taken here)
-- session 2:  update acct set balance = 999 where id = 1;
-- session 1:  select balance from acct where id = 1;          -- 100  ← snapshot is stable
-- session 1:  rollback;


-- ── §4 · Write skew & SERIALIZABLE (run in TWO sessions) ───────────────────────────────────────────────────
drop table if exists linked_account;
create table linked_account (name text primary key, balance numeric not null);
insert into linked_account values ('A', 100), ('B', 100);   -- invariant: A.balance + B.balance >= 0

-- Try it first at REPEATABLE READ — both withdrawals succeed and the invariant breaks (sum = -100):
-- session 1:  begin isolation level repeatable read; select sum(balance) from linked_account;   -- 200
-- session 2:  begin isolation level repeatable read; select sum(balance) from linked_account;   -- 200
-- session 1:  update linked_account set balance = balance - 150 where name = 'A'; commit;
-- session 2:  update linked_account set balance = balance - 150 where name = 'B'; commit;
-- (anyone):   select sum(balance) from linked_account;                                           -- -100  💥
--
-- Reset, then do the SAME interleaving at SERIALIZABLE — the second commit is rejected (SQLSTATE 40001):
-- session 1:  begin isolation level serializable; select sum(balance) from linked_account;
-- session 2:  begin isolation level serializable; select sum(balance) from linked_account;
-- session 1:  update linked_account set balance = balance - 150 where name = 'A'; commit;        -- wins
-- session 2:  update linked_account set balance = balance - 150 where name = 'B'; commit;        -- ERROR 40001
-- → the app must catch 40001 and RETRY the whole transaction.


-- ── §5 · Declarative partitioning + pruning ────────────────────────────────────────────────────────────────
drop table if exists txn_part cascade;
create table txn_part (
    id bigint generated by default as identity, account_id bigint not null,
    amount numeric(19,4) not null, created_at date not null
) partition by range (created_at);
create table txn_2026_01 partition of txn_part for values from ('2026-01-01') to ('2026-02-01');
create table txn_2026_02 partition of txn_part for values from ('2026-02-01') to ('2026-03-01');
create table txn_2026_03 partition of txn_part for values from ('2026-03-01') to ('2026-04-01');
insert into txn_part (account_id, amount, created_at)
select g, (random()*100)::numeric(19,4), date '2026-01-01' + (g % 89) from generate_series(1, 900) g;
analyze txn_part;

-- Only txn_2026_02 appears in the plan — the other partitions are pruned at plan time.
explain (analyze, buffers)
select count(*) from txn_part where created_at >= date '2026-02-01' and created_at < date '2026-03-01';


-- ── §6 · Online schema change ──────────────────────────────────────────────────────────────────────────────
-- CREATE INDEX CONCURRENTLY does not take a long table lock — but it cannot run inside a transaction block:
begin;
create index concurrently idx_bad on txn (created_at);   -- ERROR 25001: cannot run inside a transaction block
rollback;
-- In autocommit it works (Flyway must mark such a migration as not-in-transaction):
create index concurrently idx_txn_created on txn (created_at);

-- Adding a column with a CONSTANT default is metadata-only since PG 11 — instant even on a huge table:
alter table txn add column reviewed boolean not null default false;   -- no rewrite, no long lock


-- ── §7 · Read replicas (verify-adjacent — see the lesson) ──────────────────────────────────────────────────
-- On a primary with a streaming standby you would inspect lag like this (not runnable on a single node):
-- on the primary:  select client_addr, state, sent_lsn, replay_lsn,
--                         (sent_lsn - replay_lsn) as bytes_behind from pg_stat_replication;
-- on the replica:  select now() - pg_last_xact_replay_timestamp() as replication_delay;
