-- services/cif/src/main/resources/db/migration/V1__create_customer.sql
-- Flyway versioned migration. The filename encodes: V<version>__<description>.sql
-- This is the single source of truth for the schema; Hibernate (ddl-auto=validate) only checks it matches.

create table customer (
    id              bigint generated by default as identity primary key,
    customer_number varchar(20)  not null unique,
    first_name      varchar(100) not null,
    last_name       varchar(100) not null,
    email           varchar(255) not null unique,
    date_of_birth   date,
    kyc_status      varchar(20)  not null,
    created_at      timestamp(6) with time zone not null
);

-- A secondary index for lookups by email (we read /actuator and reason about indexes in Step 10).
create index idx_customer_email on customer (email);
