-- services/cif/src/main/resources/db/migration/V2__add_address_and_version.sql
-- Adds optimistic-locking version to customer, and the address table (Customer 1 -> * Address).

alter table customer add column version bigint not null default 0;

create table address (
    id          bigint generated by default as identity primary key,
    customer_id bigint       not null references customer (id),
    line1       varchar(200) not null,
    city        varchar(100) not null,
    country     varchar(2)   not null
);

create index idx_address_customer on address (customer_id);
