-- services/demand-account/src/main/resources/db/migration/V1__create_account_and_ledger.sql
-- The accounts + double-entry ledger schema. Flyway owns it; Hibernate (ddl-auto=validate) only checks
-- the entity mappings match. Money is stored as numeric(19,4) (exact decimal — never float/double).

create table account (
    id              bigint generated by default as identity primary key,
    account_number  varchar(20)    not null unique,
    currency        varchar(3)     not null,
    balance         numeric(19, 4) not null default 0,   -- materialized balance (kept in sync within a txn)
    version         bigint         not null default 0,    -- optimistic-locking version (@Version)
    created_at      timestamp(6) with time zone not null
);

-- The double-entry ledger: an append-only record of every leg of every money movement. Two entries per
-- transfer (one DEBIT, one CREDIT) share a transaction_id and sum to zero — the books always balance.
create table ledger_entry (
    id              bigint generated by default as identity primary key,
    account_id      bigint         not null references account (id),
    transaction_id  uuid           not null,
    direction       varchar(6)     not null check (direction in ('DEBIT', 'CREDIT')),
    amount          numeric(19, 4) not null check (amount > 0),
    description     varchar(200),
    created_at      timestamp(6) with time zone not null
);

create index idx_ledger_account on ledger_entry (account_id);
create index idx_ledger_transaction on ledger_entry (transaction_id);

-- An independent audit log used to demonstrate transaction propagation (REQUIRES_NEW commits separately).
create table audit_log (
    id          bigint generated by default as identity primary key,
    event       varchar(100) not null,
    detail      varchar(500),
    created_at  timestamp(6) with time zone not null
);
